# This file lists the templates to be merged into the final `bin.code-workspace` file.

extensions = [
"aaron-bond.better-comments",
"eamodio.gitlens",
"foxundermoon.shell-format",
"mads-hartmann.bash-ide-vscode",
"streetsidesoftware.code-spell-checker",
"timonwong.shellcheck",
"yzhang.markdown-all-in-one"
]
